name: Run unit test of features

on: 
  push:
    branches:
      'feature/*'

jobs:
  run-unit-test:
   runs-on: ubuntu-lastest

   steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: run unit test
      run: mvn test 
